name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image 1
      run: |
        docker build . --file app.dockerfile \
        --build-arg NEXT_PUBLIC_WS_URL=${{ secrets.NEXT_PUBLIC_WS_URL }} \
        --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
        --tag ${{ secrets.DOCKER_USERNAME }}/perplexica-app:${{ github.sha }} \
        --tag ${{ secrets.DOCKER_USERNAME }}/perplexica-app:latest

    - name: Build Docker image 2
      run: |
        docker build . --file backend-madpin.dockerfile \
        --tag ${{ secrets.DOCKER_USERNAME }}/perplexica-backend:${{ github.sha }} \
        --tag ${{ secrets.DOCKER_USERNAME }}/perplexica-backend:latest

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image 1
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/perplexica-app:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/perplexica-app:latest

    - name: Push Docker image 2
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/perplexica-backend:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/perplexica-backend:latest
